# Generated by Django 4.1.7 on 2023-05-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_pricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='cust_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='itemtable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.additem'),
        ),
    ]
