# Generated by Django 4.1.7 on 2023-05-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0004_pricelist_cust_rate_pricelist_itemtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
