# Generated by Django 4.1.7 on 2023-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0005_pricelist_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='is_active',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='status',
            field=models.TextField(default='inactive'),
        ),
    ]
