# Generated by Django 4.1.7 on 2023-05-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_remove_pricelist_is_active_pricelist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
